
# Use Ubuntu as the base image
FROM ubuntu:latest

# Install basic packages (optional)
RUN apt-get update && apt-get install -y curl vim && apt-get install -y git

# Set working directory
WORKDIR /workspace

# Default command
CMD ["bash"]
